# Generated by Django 3.0.14 on 2022-07-22 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('engine', models.IntegerField(choices=[(0, 'Report Bro - PDF')], default=0)),
                ('definition', models.TextField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'tblRole',
                'managed': True,
            },
        ),
    ]
