# Generated by Django 3.0.14 on 2022-07-22 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RoleId', models.IntegerField()),
                ('RoleName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblRole',
                'managed': True,
            },
        ),
    ]
